public class CustomTestException extends RuntimeException {
    public CustomTestException() {
        super("SUCCESS");
    }
}
